package com.cxdai.console.finance.virement.entity;

import java.util.Date;

public class AttachMent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_attachment.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_attachment.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_attachment.URL
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_attachment.TYPE
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_attachment.BUSINESS_ID
     *
     * @mbggenerated
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_attachment.BUSINESS_TYPE
     *
     * @mbggenerated
     */
    private Integer businessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_attachment.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_attachment.CARD_SHOW
     *
     * @mbggenerated
     */
    private Integer cardShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_attachment.ADDUSER
     *
     * @mbggenerated
     */
    private Integer adduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_attachment.ADDTIME
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_attachment.ADDIP
     *
     * @mbggenerated
     */
    private String addip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_attachment.UPDATEUSER
     *
     * @mbggenerated
     */
    private Integer updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_attachment.UPDATETIME
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_attachment.UPDATEIP
     *
     * @mbggenerated
     */
    private String updateip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_attachment.id
     *
     * @return the value of cw_attachment.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_attachment.id
     *
     * @param id the value for cw_attachment.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_attachment.NAME
     *
     * @return the value of cw_attachment.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_attachment.NAME
     *
     * @param name the value for cw_attachment.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_attachment.URL
     *
     * @return the value of cw_attachment.URL
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_attachment.URL
     *
     * @param url the value for cw_attachment.URL
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_attachment.TYPE
     *
     * @return the value of cw_attachment.TYPE
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_attachment.TYPE
     *
     * @param type the value for cw_attachment.TYPE
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_attachment.BUSINESS_ID
     *
     * @return the value of cw_attachment.BUSINESS_ID
     *
     * @mbggenerated
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_attachment.BUSINESS_ID
     *
     * @param businessId the value for cw_attachment.BUSINESS_ID
     *
     * @mbggenerated
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_attachment.BUSINESS_TYPE
     *
     * @return the value of cw_attachment.BUSINESS_TYPE
     *
     * @mbggenerated
     */
    public Integer getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_attachment.BUSINESS_TYPE
     *
     * @param businessType the value for cw_attachment.BUSINESS_TYPE
     *
     * @mbggenerated
     */
    public void setBusinessType(Integer businessType) {
        this.businessType = businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_attachment.STATUS
     *
     * @return the value of cw_attachment.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_attachment.STATUS
     *
     * @param status the value for cw_attachment.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_attachment.CARD_SHOW
     *
     * @return the value of cw_attachment.CARD_SHOW
     *
     * @mbggenerated
     */
    public Integer getCardShow() {
        return cardShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_attachment.CARD_SHOW
     *
     * @param cardShow the value for cw_attachment.CARD_SHOW
     *
     * @mbggenerated
     */
    public void setCardShow(Integer cardShow) {
        this.cardShow = cardShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_attachment.ADDUSER
     *
     * @return the value of cw_attachment.ADDUSER
     *
     * @mbggenerated
     */
    public Integer getAdduser() {
        return adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_attachment.ADDUSER
     *
     * @param adduser the value for cw_attachment.ADDUSER
     *
     * @mbggenerated
     */
    public void setAdduser(Integer adduser) {
        this.adduser = adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_attachment.ADDTIME
     *
     * @return the value of cw_attachment.ADDTIME
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_attachment.ADDTIME
     *
     * @param addtime the value for cw_attachment.ADDTIME
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_attachment.ADDIP
     *
     * @return the value of cw_attachment.ADDIP
     *
     * @mbggenerated
     */
    public String getAddip() {
        return addip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_attachment.ADDIP
     *
     * @param addip the value for cw_attachment.ADDIP
     *
     * @mbggenerated
     */
    public void setAddip(String addip) {
        this.addip = addip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_attachment.UPDATEUSER
     *
     * @return the value of cw_attachment.UPDATEUSER
     *
     * @mbggenerated
     */
    public Integer getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_attachment.UPDATEUSER
     *
     * @param updateuser the value for cw_attachment.UPDATEUSER
     *
     * @mbggenerated
     */
    public void setUpdateuser(Integer updateuser) {
        this.updateuser = updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_attachment.UPDATETIME
     *
     * @return the value of cw_attachment.UPDATETIME
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_attachment.UPDATETIME
     *
     * @param updatetime the value for cw_attachment.UPDATETIME
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_attachment.UPDATEIP
     *
     * @return the value of cw_attachment.UPDATEIP
     *
     * @mbggenerated
     */
    public String getUpdateip() {
        return updateip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_attachment.UPDATEIP
     *
     * @param updateip the value for cw_attachment.UPDATEIP
     *
     * @mbggenerated
     */
    public void setUpdateip(String updateip) {
        this.updateip = updateip;
    }
}