package com.cxdai.console.finance.virement.entity;

import java.util.Date;

public class BankAccountInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_bank_account_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_bank_account_info.PAY_NAME
     *
     * @mbggenerated
     */
    private String payName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_bank_account_info.BANK_ID
     *
     * @mbggenerated
     */
    private Integer bankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_bank_account_info.SUBBRANCH
     *
     * @mbggenerated
     */
    private String subbranch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_bank_account_info.CARD_NO
     *
     * @mbggenerated
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_bank_account_info.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_bank_account_info.ADDUSER
     *
     * @mbggenerated
     */
    private Integer adduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_bank_account_info.ADDTIME
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_bank_account_info.ADDIP
     *
     * @mbggenerated
     */
    private String addip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_bank_account_info.UPDATEUSER
     *
     * @mbggenerated
     */
    private Integer updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_bank_account_info.UPDATETIME
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_bank_account_info.UPDATEIP
     *
     * @mbggenerated
     */
    private String updateip;
    private Integer type;
    
    
    
	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_bank_account_info.id
     *
     * @return the value of cw_bank_account_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_bank_account_info.id
     *
     * @param id the value for cw_bank_account_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_bank_account_info.PAY_NAME
     *
     * @return the value of cw_bank_account_info.PAY_NAME
     *
     * @mbggenerated
     */
    public String getPayName() {
        return payName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_bank_account_info.PAY_NAME
     *
     * @param payName the value for cw_bank_account_info.PAY_NAME
     *
     * @mbggenerated
     */
    public void setPayName(String payName) {
        this.payName = payName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_bank_account_info.BANK_ID
     *
     * @return the value of cw_bank_account_info.BANK_ID
     *
     * @mbggenerated
     */
    public Integer getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_bank_account_info.BANK_ID
     *
     * @param bankId the value for cw_bank_account_info.BANK_ID
     *
     * @mbggenerated
     */
    public void setBankId(Integer bankId) {
        this.bankId = bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_bank_account_info.SUBBRANCH
     *
     * @return the value of cw_bank_account_info.SUBBRANCH
     *
     * @mbggenerated
     */
    public String getSubbranch() {
        return subbranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_bank_account_info.SUBBRANCH
     *
     * @param subbranch the value for cw_bank_account_info.SUBBRANCH
     *
     * @mbggenerated
     */
    public void setSubbranch(String subbranch) {
        this.subbranch = subbranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_bank_account_info.CARD_NO
     *
     * @return the value of cw_bank_account_info.CARD_NO
     *
     * @mbggenerated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_bank_account_info.CARD_NO
     *
     * @param cardNo the value for cw_bank_account_info.CARD_NO
     *
     * @mbggenerated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_bank_account_info.STATUS
     *
     * @return the value of cw_bank_account_info.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_bank_account_info.STATUS
     *
     * @param status the value for cw_bank_account_info.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_bank_account_info.ADDUSER
     *
     * @return the value of cw_bank_account_info.ADDUSER
     *
     * @mbggenerated
     */
    public Integer getAdduser() {
        return adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_bank_account_info.ADDUSER
     *
     * @param adduser the value for cw_bank_account_info.ADDUSER
     *
     * @mbggenerated
     */
    public void setAdduser(Integer adduser) {
        this.adduser = adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_bank_account_info.ADDTIME
     *
     * @return the value of cw_bank_account_info.ADDTIME
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_bank_account_info.ADDTIME
     *
     * @param addtime the value for cw_bank_account_info.ADDTIME
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_bank_account_info.ADDIP
     *
     * @return the value of cw_bank_account_info.ADDIP
     *
     * @mbggenerated
     */
    public String getAddip() {
        return addip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_bank_account_info.ADDIP
     *
     * @param addip the value for cw_bank_account_info.ADDIP
     *
     * @mbggenerated
     */
    public void setAddip(String addip) {
        this.addip = addip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_bank_account_info.UPDATEUSER
     *
     * @return the value of cw_bank_account_info.UPDATEUSER
     *
     * @mbggenerated
     */
    public Integer getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_bank_account_info.UPDATEUSER
     *
     * @param updateuser the value for cw_bank_account_info.UPDATEUSER
     *
     * @mbggenerated
     */
    public void setUpdateuser(Integer updateuser) {
        this.updateuser = updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_bank_account_info.UPDATETIME
     *
     * @return the value of cw_bank_account_info.UPDATETIME
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_bank_account_info.UPDATETIME
     *
     * @param updatetime the value for cw_bank_account_info.UPDATETIME
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_bank_account_info.UPDATEIP
     *
     * @return the value of cw_bank_account_info.UPDATEIP
     *
     * @mbggenerated
     */
    public String getUpdateip() {
        return updateip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_bank_account_info.UPDATEIP
     *
     * @param updateip the value for cw_bank_account_info.UPDATEIP
     *
     * @mbggenerated
     */
    public void setUpdateip(String updateip) {
        this.updateip = updateip;
    }
}