package com.cxdai.console.finance.virement.entity;

import java.math.BigDecimal;
import java.util.Date;

public class BreakEvenAnalysis {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_breakeven_analysis.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_breakeven_analysis.INCOME
     *
     * @mbggenerated
     */
    private BigDecimal income;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_breakeven_analysis.PAY
     *
     * @mbggenerated
     */
    private BigDecimal pay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_breakeven_analysis.NET_PROCEEDS
     *
     * @mbggenerated
     */
    private BigDecimal netProceeds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_breakeven_analysis.RECHARGE
     *
     * @mbggenerated
     */
    private BigDecimal recharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_breakeven_analysis.ADVANCE
     *
     * @mbggenerated
     */
    private BigDecimal advance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_breakeven_analysis.NET_FLOW
     *
     * @mbggenerated
     */
    private BigDecimal netFlow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_breakeven_analysis.INCOME_RATE
     *
     * @mbggenerated
     */
    private String incomeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_breakeven_analysis.PAY_RATE
     *
     * @mbggenerated
     */
    private String payRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_breakeven_analysis.RECHARGE_RATE
     *
     * @mbggenerated
     */
    private String rechargeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_breakeven_analysis.RECORDE_RATE
     *
     * @mbggenerated
     */
    private String recordeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_breakeven_analysis.ALL_PRINCIPAL
     *
     * @mbggenerated
     */
    private BigDecimal allPrincipal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_breakeven_analysis.THROUGH_PRINCIPAL
     *
     * @mbggenerated
     */
    private BigDecimal throughPrincipal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_breakeven_analysis.EXPECT_RATE
     *
     * @mbggenerated
     */
    private String expectRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_breakeven_analysis.EXPECT_CASH
     *
     * @mbggenerated
     */
    private BigDecimal expectCash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_breakeven_analysis.ACTUAL_RATE
     *
     * @mbggenerated
     */
    private String actualRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_breakeven_analysis.ADD_TIME
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_breakeven_analysis.TIME
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_breakeven_analysis.TYPE
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_breakeven_analysis.ID
     *
     * @return the value of cw_breakeven_analysis.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_breakeven_analysis.ID
     *
     * @param id the value for cw_breakeven_analysis.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_breakeven_analysis.INCOME
     *
     * @return the value of cw_breakeven_analysis.INCOME
     *
     * @mbggenerated
     */
    public BigDecimal getIncome() {
        return income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_breakeven_analysis.INCOME
     *
     * @param income the value for cw_breakeven_analysis.INCOME
     *
     * @mbggenerated
     */
    public void setIncome(BigDecimal income) {
        this.income = income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_breakeven_analysis.PAY
     *
     * @return the value of cw_breakeven_analysis.PAY
     *
     * @mbggenerated
     */
    public BigDecimal getPay() {
        return pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_breakeven_analysis.PAY
     *
     * @param pay the value for cw_breakeven_analysis.PAY
     *
     * @mbggenerated
     */
    public void setPay(BigDecimal pay) {
        this.pay = pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_breakeven_analysis.NET_PROCEEDS
     *
     * @return the value of cw_breakeven_analysis.NET_PROCEEDS
     *
     * @mbggenerated
     */
    public BigDecimal getNetProceeds() {
        return netProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_breakeven_analysis.NET_PROCEEDS
     *
     * @param netProceeds the value for cw_breakeven_analysis.NET_PROCEEDS
     *
     * @mbggenerated
     */
    public void setNetProceeds(BigDecimal netProceeds) {
        this.netProceeds = netProceeds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_breakeven_analysis.RECHARGE
     *
     * @return the value of cw_breakeven_analysis.RECHARGE
     *
     * @mbggenerated
     */
    public BigDecimal getRecharge() {
        return recharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_breakeven_analysis.RECHARGE
     *
     * @param recharge the value for cw_breakeven_analysis.RECHARGE
     *
     * @mbggenerated
     */
    public void setRecharge(BigDecimal recharge) {
        this.recharge = recharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_breakeven_analysis.ADVANCE
     *
     * @return the value of cw_breakeven_analysis.ADVANCE
     *
     * @mbggenerated
     */
    public BigDecimal getAdvance() {
        return advance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_breakeven_analysis.ADVANCE
     *
     * @param advance the value for cw_breakeven_analysis.ADVANCE
     *
     * @mbggenerated
     */
    public void setAdvance(BigDecimal advance) {
        this.advance = advance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_breakeven_analysis.NET_FLOW
     *
     * @return the value of cw_breakeven_analysis.NET_FLOW
     *
     * @mbggenerated
     */
    public BigDecimal getNetFlow() {
        return netFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_breakeven_analysis.NET_FLOW
     *
     * @param netFlow the value for cw_breakeven_analysis.NET_FLOW
     *
     * @mbggenerated
     */
    public void setNetFlow(BigDecimal netFlow) {
        this.netFlow = netFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_breakeven_analysis.INCOME_RATE
     *
     * @return the value of cw_breakeven_analysis.INCOME_RATE
     *
     * @mbggenerated
     */
    public String getIncomeRate() {
        return incomeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_breakeven_analysis.INCOME_RATE
     *
     * @param incomeRate the value for cw_breakeven_analysis.INCOME_RATE
     *
     * @mbggenerated
     */
    public void setIncomeRate(String incomeRate) {
        this.incomeRate = incomeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_breakeven_analysis.PAY_RATE
     *
     * @return the value of cw_breakeven_analysis.PAY_RATE
     *
     * @mbggenerated
     */
    public String getPayRate() {
        return payRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_breakeven_analysis.PAY_RATE
     *
     * @param payRate the value for cw_breakeven_analysis.PAY_RATE
     *
     * @mbggenerated
     */
    public void setPayRate(String payRate) {
        this.payRate = payRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_breakeven_analysis.RECHARGE_RATE
     *
     * @return the value of cw_breakeven_analysis.RECHARGE_RATE
     *
     * @mbggenerated
     */
    public String getRechargeRate() {
        return rechargeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_breakeven_analysis.RECHARGE_RATE
     *
     * @param rechargeRate the value for cw_breakeven_analysis.RECHARGE_RATE
     *
     * @mbggenerated
     */
    public void setRechargeRate(String rechargeRate) {
        this.rechargeRate = rechargeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_breakeven_analysis.RECORDE_RATE
     *
     * @return the value of cw_breakeven_analysis.RECORDE_RATE
     *
     * @mbggenerated
     */
    public String getRecordeRate() {
        return recordeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_breakeven_analysis.RECORDE_RATE
     *
     * @param recordeRate the value for cw_breakeven_analysis.RECORDE_RATE
     *
     * @mbggenerated
     */
    public void setRecordeRate(String recordeRate) {
        this.recordeRate = recordeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_breakeven_analysis.ALL_PRINCIPAL
     *
     * @return the value of cw_breakeven_analysis.ALL_PRINCIPAL
     *
     * @mbggenerated
     */
    public BigDecimal getAllPrincipal() {
        return allPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_breakeven_analysis.ALL_PRINCIPAL
     *
     * @param allPrincipal the value for cw_breakeven_analysis.ALL_PRINCIPAL
     *
     * @mbggenerated
     */
    public void setAllPrincipal(BigDecimal allPrincipal) {
        this.allPrincipal = allPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_breakeven_analysis.THROUGH_PRINCIPAL
     *
     * @return the value of cw_breakeven_analysis.THROUGH_PRINCIPAL
     *
     * @mbggenerated
     */
    public BigDecimal getThroughPrincipal() {
        return throughPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_breakeven_analysis.THROUGH_PRINCIPAL
     *
     * @param throughPrincipal the value for cw_breakeven_analysis.THROUGH_PRINCIPAL
     *
     * @mbggenerated
     */
    public void setThroughPrincipal(BigDecimal throughPrincipal) {
        this.throughPrincipal = throughPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_breakeven_analysis.EXPECT_RATE
     *
     * @return the value of cw_breakeven_analysis.EXPECT_RATE
     *
     * @mbggenerated
     */
    public String getExpectRate() {
        return expectRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_breakeven_analysis.EXPECT_RATE
     *
     * @param expectRate the value for cw_breakeven_analysis.EXPECT_RATE
     *
     * @mbggenerated
     */
    public void setExpectRate(String expectRate) {
        this.expectRate = expectRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_breakeven_analysis.EXPECT_CASH
     *
     * @return the value of cw_breakeven_analysis.EXPECT_CASH
     *
     * @mbggenerated
     */
    public BigDecimal getExpectCash() {
        return expectCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_breakeven_analysis.EXPECT_CASH
     *
     * @param expectCash the value for cw_breakeven_analysis.EXPECT_CASH
     *
     * @mbggenerated
     */
    public void setExpectCash(BigDecimal expectCash) {
        this.expectCash = expectCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_breakeven_analysis.ACTUAL_RATE
     *
     * @return the value of cw_breakeven_analysis.ACTUAL_RATE
     *
     * @mbggenerated
     */
    public String getActualRate() {
        return actualRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_breakeven_analysis.ACTUAL_RATE
     *
     * @param actualRate the value for cw_breakeven_analysis.ACTUAL_RATE
     *
     * @mbggenerated
     */
    public void setActualRate(String actualRate) {
        this.actualRate = actualRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_breakeven_analysis.ADD_TIME
     *
     * @return the value of cw_breakeven_analysis.ADD_TIME
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_breakeven_analysis.ADD_TIME
     *
     * @param addTime the value for cw_breakeven_analysis.ADD_TIME
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_breakeven_analysis.TIME
     *
     * @return the value of cw_breakeven_analysis.TIME
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_breakeven_analysis.TIME
     *
     * @param time the value for cw_breakeven_analysis.TIME
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_breakeven_analysis.TYPE
     *
     * @return the value of cw_breakeven_analysis.TYPE
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_breakeven_analysis.TYPE
     *
     * @param type the value for cw_breakeven_analysis.TYPE
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }
}