package com.cxdai.console.finance.virement.entity;

import java.math.BigDecimal;
import java.util.Date;

public class CheckWithdrawals {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_check_withdrawals.ID
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_check_withdrawals.BILL_DATE
	 *
	 * @mbggenerated
	 */
	private Date billDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_check_withdrawals.PRESENT_SUCCESS_MONEY
	 *
	 * @mbggenerated
	 */
	private BigDecimal presentSuccessMoney;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_check_withdrawals.TAKE_CASH_MONEY
	 *
	 * @mbggenerated
	 */
	private BigDecimal takeCashMoney;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_check_withdrawals.ACTUAL_CASH_MONEY
	 *
	 * @mbggenerated
	 */
	private BigDecimal actualCashMoney;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_check_withdrawals.TOTAL_EXPENDITURE
	 *
	 * @mbggenerated
	 */
	private BigDecimal totalExpenditure;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_check_withdrawals.COUNTER_FEE
	 *
	 * @mbggenerated
	 */
	private BigDecimal counterFee;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_check_withdrawals.DIFFERENCE
	 *
	 * @mbggenerated
	 */
	private BigDecimal difference;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_check_withdrawals.REMARKS
	 *
	 * @mbggenerated
	 */
	private String remarks;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_check_withdrawals.IS_SUCCESS
	 *
	 * @mbggenerated
	 */
	private Integer isSuccess;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_check_withdrawals.STATUS
	 *
	 * @mbggenerated
	 */
	private Integer status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_check_withdrawals.VERIFY_TIME
	 *
	 * @mbggenerated
	 */
	private Date verifyTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_check_withdrawals.ADD_USER
	 *
	 * @mbggenerated
	 */
	private Integer addUser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_check_withdrawals.ADD_TIME
	 *
	 * @mbggenerated
	 */
	private Date addTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_check_withdrawals.ADD_IP
	 *
	 * @mbggenerated
	 */
	private String addIp;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_check_withdrawals.UPDATE_USER
	 *
	 * @mbggenerated
	 */
	private Integer updateUser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_check_withdrawals.UPDATE_TIME
	 *
	 * @mbggenerated
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_check_withdrawals.UPDATE_IP
	 *
	 * @mbggenerated
	 */
	private String updateIp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_check_withdrawals.ID
	 *
	 * @return the value of cw_check_withdrawals.ID
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_check_withdrawals.ID
	 *
	 * @param id
	 *            the value for cw_check_withdrawals.ID
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_check_withdrawals.BILL_DATE
	 *
	 * @return the value of cw_check_withdrawals.BILL_DATE
	 *
	 * @mbggenerated
	 */
	public Date getBillDate() {
		return billDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_check_withdrawals.BILL_DATE
	 *
	 * @param billDate
	 *            the value for cw_check_withdrawals.BILL_DATE
	 *
	 * @mbggenerated
	 */
	public void setBillDate(Date billDate) {
		this.billDate = billDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_check_withdrawals.PRESENT_SUCCESS_MONEY
	 *
	 * @return the value of cw_check_withdrawals.PRESENT_SUCCESS_MONEY
	 *
	 * @mbggenerated
	 */
	public BigDecimal getPresentSuccessMoney() {
		return presentSuccessMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_check_withdrawals.PRESENT_SUCCESS_MONEY
	 *
	 * @param presentSuccessMoney
	 *            the value for cw_check_withdrawals.PRESENT_SUCCESS_MONEY
	 *
	 * @mbggenerated
	 */
	public void setPresentSuccessMoney(BigDecimal presentSuccessMoney) {
		this.presentSuccessMoney = presentSuccessMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_check_withdrawals.TAKE_CASH_MONEY
	 *
	 * @return the value of cw_check_withdrawals.TAKE_CASH_MONEY
	 *
	 * @mbggenerated
	 */
	public BigDecimal getTakeCashMoney() {
		return takeCashMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_check_withdrawals.TAKE_CASH_MONEY
	 *
	 * @param takeCashMoney
	 *            the value for cw_check_withdrawals.TAKE_CASH_MONEY
	 *
	 * @mbggenerated
	 */
	public void setTakeCashMoney(BigDecimal takeCashMoney) {
		this.takeCashMoney = takeCashMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_check_withdrawals.ACTUAL_CASH_MONEY
	 *
	 * @return the value of cw_check_withdrawals.ACTUAL_CASH_MONEY
	 *
	 * @mbggenerated
	 */
	public BigDecimal getActualCashMoney() {
		return actualCashMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_check_withdrawals.ACTUAL_CASH_MONEY
	 *
	 * @param actualCashMoney
	 *            the value for cw_check_withdrawals.ACTUAL_CASH_MONEY
	 *
	 * @mbggenerated
	 */
	public void setActualCashMoney(BigDecimal actualCashMoney) {
		this.actualCashMoney = actualCashMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_check_withdrawals.TOTAL_EXPENDITURE
	 *
	 * @return the value of cw_check_withdrawals.TOTAL_EXPENDITURE
	 *
	 * @mbggenerated
	 */
	public BigDecimal getTotalExpenditure() {
		return totalExpenditure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_check_withdrawals.TOTAL_EXPENDITURE
	 *
	 * @param totalExpenditure
	 *            the value for cw_check_withdrawals.TOTAL_EXPENDITURE
	 *
	 * @mbggenerated
	 */
	public void setTotalExpenditure(BigDecimal totalExpenditure) {
		this.totalExpenditure = totalExpenditure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_check_withdrawals.COUNTER_FEE
	 *
	 * @return the value of cw_check_withdrawals.COUNTER_FEE
	 *
	 * @mbggenerated
	 */
	public BigDecimal getCounterFee() {
		return counterFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_check_withdrawals.COUNTER_FEE
	 *
	 * @param counterFee
	 *            the value for cw_check_withdrawals.COUNTER_FEE
	 *
	 * @mbggenerated
	 */
	public void setCounterFee(BigDecimal counterFee) {
		this.counterFee = counterFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_check_withdrawals.DIFFERENCE
	 *
	 * @return the value of cw_check_withdrawals.DIFFERENCE
	 *
	 * @mbggenerated
	 */
	public BigDecimal getDifference() {
		return difference;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_check_withdrawals.DIFFERENCE
	 *
	 * @param difference
	 *            the value for cw_check_withdrawals.DIFFERENCE
	 *
	 * @mbggenerated
	 */
	public void setDifference(BigDecimal difference) {
		this.difference = difference;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_check_withdrawals.REMARKS
	 *
	 * @return the value of cw_check_withdrawals.REMARKS
	 *
	 * @mbggenerated
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_check_withdrawals.REMARKS
	 *
	 * @param remarks
	 *            the value for cw_check_withdrawals.REMARKS
	 *
	 * @mbggenerated
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_check_withdrawals.IS_SUCCESS
	 *
	 * @return the value of cw_check_withdrawals.IS_SUCCESS
	 *
	 * @mbggenerated
	 */
	public Integer getIsSuccess() {
		return isSuccess;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_check_withdrawals.IS_SUCCESS
	 *
	 * @param isSuccess
	 *            the value for cw_check_withdrawals.IS_SUCCESS
	 *
	 * @mbggenerated
	 */
	public void setIsSuccess(Integer isSuccess) {
		this.isSuccess = isSuccess;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_check_withdrawals.STATUS
	 *
	 * @return the value of cw_check_withdrawals.STATUS
	 *
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_check_withdrawals.STATUS
	 *
	 * @param status
	 *            the value for cw_check_withdrawals.STATUS
	 *
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_check_withdrawals.VERIFY_TIME
	 *
	 * @return the value of cw_check_withdrawals.VERIFY_TIME
	 *
	 * @mbggenerated
	 */
	public Date getVerifyTime() {
		return verifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_check_withdrawals.VERIFY_TIME
	 *
	 * @param verifyTime
	 *            the value for cw_check_withdrawals.VERIFY_TIME
	 *
	 * @mbggenerated
	 */
	public void setVerifyTime(Date verifyTime) {
		this.verifyTime = verifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_check_withdrawals.ADD_USER
	 *
	 * @return the value of cw_check_withdrawals.ADD_USER
	 *
	 * @mbggenerated
	 */
	public Integer getAddUser() {
		return addUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_check_withdrawals.ADD_USER
	 *
	 * @param addUser
	 *            the value for cw_check_withdrawals.ADD_USER
	 *
	 * @mbggenerated
	 */
	public void setAddUser(Integer addUser) {
		this.addUser = addUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_check_withdrawals.ADD_TIME
	 *
	 * @return the value of cw_check_withdrawals.ADD_TIME
	 *
	 * @mbggenerated
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_check_withdrawals.ADD_TIME
	 *
	 * @param addTime
	 *            the value for cw_check_withdrawals.ADD_TIME
	 *
	 * @mbggenerated
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_check_withdrawals.ADD_IP
	 *
	 * @return the value of cw_check_withdrawals.ADD_IP
	 *
	 * @mbggenerated
	 */
	public String getAddIp() {
		return addIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_check_withdrawals.ADD_IP
	 *
	 * @param addIp
	 *            the value for cw_check_withdrawals.ADD_IP
	 *
	 * @mbggenerated
	 */
	public void setAddIp(String addIp) {
		this.addIp = addIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_check_withdrawals.UPDATE_USER
	 *
	 * @return the value of cw_check_withdrawals.UPDATE_USER
	 *
	 * @mbggenerated
	 */
	public Integer getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_check_withdrawals.UPDATE_USER
	 *
	 * @param updateUser
	 *            the value for cw_check_withdrawals.UPDATE_USER
	 *
	 * @mbggenerated
	 */
	public void setUpdateUser(Integer updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_check_withdrawals.UPDATE_TIME
	 *
	 * @return the value of cw_check_withdrawals.UPDATE_TIME
	 *
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_check_withdrawals.UPDATE_TIME
	 *
	 * @param updateTime
	 *            the value for cw_check_withdrawals.UPDATE_TIME
	 *
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_check_withdrawals.UPDATE_IP
	 *
	 * @return the value of cw_check_withdrawals.UPDATE_IP
	 *
	 * @mbggenerated
	 */
	public String getUpdateIp() {
		return updateIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_check_withdrawals.UPDATE_IP
	 *
	 * @param updateIp
	 *            the value for cw_check_withdrawals.UPDATE_IP
	 *
	 * @mbggenerated
	 */
	public void setUpdateIp(String updateIp) {
		this.updateIp = updateIp;
	}

	private String billDateStr;

	public String getBillDateStr() {
		return billDateStr;
	}

	public void setBillDateStr(String billDateStr) {
		this.billDateStr = billDateStr;
	}

}