package com.cxdai.console.finance.virement.entity;

import java.math.BigDecimal;
import java.util.Date;

/****
 * 现金日记账实体类
 * 
 * @author Administrator
 *
 */
public class Journal {

	/****
	 * 1：正常
	 */
	public static final Byte STATUS_NOMAL = 1;

	/***
	 * 删除
	 */
	public static final Byte STATUS_DELETE = 2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_journal.ID
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * <p>
	 * 操作日期
	 * </p>
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_journal.OPERATION_DATE
	 *
	 * @mbggenerated
	 */
	private Date operationDate;

	/**
	 * <p>
	 * 借方金额
	 * </p>
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_journal.DEBIT_AMOUNT
	 *
	 * @mbggenerated
	 */
	private BigDecimal debitAmount;

	/**
	 * <p>
	 * 贷方金额
	 * </p>
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_journal.CREDIT_AMOUNT
	 *
	 * @mbggenerated
	 */
	private BigDecimal creditAmount;

	/**
	 * <p>
	 * 状态
	 * </p>
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_journal.STATUS
	 *
	 * @mbggenerated
	 */
	private Byte status;

	/**
	 * <p>
	 * 结余金额
	 * </p>
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_journal.BALANCE
	 *
	 * @mbggenerated
	 */
	private BigDecimal balance;

	/**
	 * <p>
	 * 摘要
	 * </p>
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_journal.REMARK
	 *
	 * @mbggenerated
	 */
	private String remark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_journal.ADDTIME
	 *
	 * @mbggenerated
	 */
	private Date addtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_journal.ADDUSER
	 *
	 * @mbggenerated
	 */
	private Integer adduser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_journal.ADDIP
	 *
	 * @mbggenerated
	 */
	private String addip;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_journal.UPDATETIME
	 *
	 * @mbggenerated
	 */
	private Date updatetime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_journal.UPDATEUSER
	 *
	 * @mbggenerated
	 */
	private Integer updateuser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_journal.UPDATEIP
	 *
	 * @mbggenerated
	 */
	private String updateip;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_journal.ID
	 *
	 * @return the value of cw_journal.ID
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_journal.ID
	 *
	 * @param id
	 *            the value for cw_journal.ID
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_journal.OPERATION_DATE
	 *
	 * @return the value of cw_journal.OPERATION_DATE
	 *
	 * @mbggenerated
	 */
	public Date getOperationDate() {
		return operationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_journal.OPERATION_DATE
	 *
	 * @param operationDate
	 *            the value for cw_journal.OPERATION_DATE
	 *
	 * @mbggenerated
	 */
	public void setOperationDate(Date operationDate) {
		this.operationDate = operationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_journal.DEBIT_AMOUNT
	 *
	 * @return the value of cw_journal.DEBIT_AMOUNT
	 *
	 * @mbggenerated
	 */
	public BigDecimal getDebitAmount() {
		return debitAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_journal.DEBIT_AMOUNT
	 *
	 * @param debitAmount
	 *            the value for cw_journal.DEBIT_AMOUNT
	 *
	 * @mbggenerated
	 */
	public void setDebitAmount(BigDecimal debitAmount) {
		this.debitAmount = debitAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_journal.CREDIT_AMOUNT
	 *
	 * @return the value of cw_journal.CREDIT_AMOUNT
	 *
	 * @mbggenerated
	 */
	public BigDecimal getCreditAmount() {
		return creditAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_journal.CREDIT_AMOUNT
	 *
	 * @param creditAmount
	 *            the value for cw_journal.CREDIT_AMOUNT
	 *
	 * @mbggenerated
	 */
	public void setCreditAmount(BigDecimal creditAmount) {
		this.creditAmount = creditAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_journal.STATUS
	 *
	 * @return the value of cw_journal.STATUS
	 *
	 * @mbggenerated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_journal.STATUS
	 *
	 * @param status
	 *            the value for cw_journal.STATUS
	 *
	 * @mbggenerated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_journal.BALANCE
	 *
	 * @return the value of cw_journal.BALANCE
	 *
	 * @mbggenerated
	 */
	public BigDecimal getBalance() {
		return balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_journal.BALANCE
	 *
	 * @param balance
	 *            the value for cw_journal.BALANCE
	 *
	 * @mbggenerated
	 */
	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_journal.REMARK
	 *
	 * @return the value of cw_journal.REMARK
	 *
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_journal.REMARK
	 *
	 * @param remark
	 *            the value for cw_journal.REMARK
	 *
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_journal.ADDTIME
	 *
	 * @return the value of cw_journal.ADDTIME
	 *
	 * @mbggenerated
	 */
	public Date getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_journal.ADDTIME
	 *
	 * @param addtime
	 *            the value for cw_journal.ADDTIME
	 *
	 * @mbggenerated
	 */
	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_journal.ADDUSER
	 *
	 * @return the value of cw_journal.ADDUSER
	 *
	 * @mbggenerated
	 */
	public Integer getAdduser() {
		return adduser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_journal.ADDUSER
	 *
	 * @param adduser
	 *            the value for cw_journal.ADDUSER
	 *
	 * @mbggenerated
	 */
	public void setAdduser(Integer adduser) {
		this.adduser = adduser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_journal.ADDIP
	 *
	 * @return the value of cw_journal.ADDIP
	 *
	 * @mbggenerated
	 */
	public String getAddip() {
		return addip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_journal.ADDIP
	 *
	 * @param addip
	 *            the value for cw_journal.ADDIP
	 *
	 * @mbggenerated
	 */
	public void setAddip(String addip) {
		this.addip = addip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_journal.UPDATETIME
	 *
	 * @return the value of cw_journal.UPDATETIME
	 *
	 * @mbggenerated
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_journal.UPDATETIME
	 *
	 * @param updatetime
	 *            the value for cw_journal.UPDATETIME
	 *
	 * @mbggenerated
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_journal.UPDATEUSER
	 *
	 * @return the value of cw_journal.UPDATEUSER
	 *
	 * @mbggenerated
	 */
	public Integer getUpdateuser() {
		return updateuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_journal.UPDATEUSER
	 *
	 * @param updateuser
	 *            the value for cw_journal.UPDATEUSER
	 *
	 * @mbggenerated
	 */
	public void setUpdateuser(Integer updateuser) {
		this.updateuser = updateuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_journal.UPDATEIP
	 *
	 * @return the value of cw_journal.UPDATEIP
	 *
	 * @mbggenerated
	 */
	public String getUpdateip() {
		return updateip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_journal.UPDATEIP
	 *
	 * @param updateip
	 *            the value for cw_journal.UPDATEIP
	 *
	 * @mbggenerated
	 */
	public void setUpdateip(String updateip) {
		this.updateip = updateip;
	}

	/***
	 * 1:现金日记账
	 */
	public static final Byte TYPE_JOURNAL = 1;
	/***
	 * 2:第三方平台数据明细账
	 */
	public static final Byte TYPE_OTHER_PLATFORM = 2;
	private Byte type;// 现金日记账类型
	private Byte thirdPlatform;// 第三方平台,当type=2时存在

	public Byte getType() {
		return type;
	}

	public void setType(Byte type) {
		this.type = type;
	}

	public Byte getThirdPlatform() {
		return thirdPlatform;
	}

	public void setThirdPlatform(Byte thirdPlatform) {
		this.thirdPlatform = thirdPlatform;
	}

}