package com.cxdai.console.finance.virement.entity;

import java.math.BigDecimal;
import java.util.Date;

public class MoneyOperation {
	/***
	 * 1:内部转账
	 */
	public static final Integer INTER_TRANSFER_TYPE = 1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.OPERATION_CODE
	 *
	 * @mbggenerated
	 */
	private String operationCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.OPERATIONR_MONEY
	 *
	 * @mbggenerated
	 */
	private BigDecimal operationrMoney;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.OUT_BANK_ACCOUNT_ID
	 *
	 * @mbggenerated
	 */
	private Integer outBankAccountId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.OUT_TYPE
	 *
	 * @mbggenerated
	 */
	private Integer outType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.PAYER_NAME
	 *
	 * @mbggenerated
	 */
	private String payerName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.PAYER_BANK_ID
	 *
	 * @mbggenerated
	 */
	private Integer payerBankId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.PAYER_SUBBRANCH
	 *
	 * @mbggenerated
	 */
	private String payerSubbranch;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.PAYER_CARD_NO
	 *
	 * @mbggenerated
	 */
	private String payerCardNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.IN_BANK_ACCOUNT_ID
	 *
	 * @mbggenerated
	 */
	private Integer inBankAccountId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.IN_TYPE
	 *
	 * @mbggenerated
	 */
	private Integer inType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.PAYEE_NAME
	 *
	 * @mbggenerated
	 */
	private String payeeName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.PAYEE_BANK_ID
	 *
	 * @mbggenerated
	 */
	private Integer payeeBankId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.PAYEE_SUBBRANCH
	 *
	 * @mbggenerated
	 */
	private String payeeSubbranch;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.PAYEE_CARD_NO
	 *
	 * @mbggenerated
	 */
	private String payeeCardNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.STATUS
	 *
	 * @mbggenerated
	 */
	private Integer status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.OPERATION_TYPE
	 *
	 * @mbggenerated
	 */
	private Integer operationType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.BUSINESS_TIME
	 *
	 * @mbggenerated
	 */
	private Date businessTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.REMARK
	 *
	 * @mbggenerated
	 */
	private String remark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.ADDUSER
	 *
	 * @mbggenerated
	 */
	private Integer adduser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.ADDTIME
	 *
	 * @mbggenerated
	 */
	private Date addtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.ADDIP
	 *
	 * @mbggenerated
	 */
	private String addip;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.UPDATEUSER
	 *
	 * @mbggenerated
	 */
	private Integer updateuser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.UPDATETIME
	 *
	 * @mbggenerated
	 */
	private Date updatetime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cw_money_operation.UPDATEIP
	 *
	 * @mbggenerated
	 */
	private String updateip;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.id
	 *
	 * @return the value of cw_money_operation.id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.id
	 *
	 * @param id
	 *            the value for cw_money_operation.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.OPERATION_CODE
	 *
	 * @return the value of cw_money_operation.OPERATION_CODE
	 *
	 * @mbggenerated
	 */
	public String getOperationCode() {
		return operationCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.OPERATION_CODE
	 *
	 * @param operationCode
	 *            the value for cw_money_operation.OPERATION_CODE
	 *
	 * @mbggenerated
	 */
	public void setOperationCode(String operationCode) {
		this.operationCode = operationCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.OPERATIONR_MONEY
	 *
	 * @return the value of cw_money_operation.OPERATIONR_MONEY
	 *
	 * @mbggenerated
	 */
	public BigDecimal getOperationrMoney() {
		return operationrMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.OPERATIONR_MONEY
	 *
	 * @param operationrMoney
	 *            the value for cw_money_operation.OPERATIONR_MONEY
	 *
	 * @mbggenerated
	 */
	public void setOperationrMoney(BigDecimal operationrMoney) {
		this.operationrMoney = operationrMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.OUT_BANK_ACCOUNT_ID
	 *
	 * @return the value of cw_money_operation.OUT_BANK_ACCOUNT_ID
	 *
	 * @mbggenerated
	 */
	public Integer getOutBankAccountId() {
		return outBankAccountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.OUT_BANK_ACCOUNT_ID
	 *
	 * @param outBankAccountId
	 *            the value for cw_money_operation.OUT_BANK_ACCOUNT_ID
	 *
	 * @mbggenerated
	 */
	public void setOutBankAccountId(Integer outBankAccountId) {
		this.outBankAccountId = outBankAccountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.OUT_TYPE
	 *
	 * @return the value of cw_money_operation.OUT_TYPE
	 *
	 * @mbggenerated
	 */
	public Integer getOutType() {
		return outType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.OUT_TYPE
	 *
	 * @param outType
	 *            the value for cw_money_operation.OUT_TYPE
	 *
	 * @mbggenerated
	 */
	public void setOutType(Integer outType) {
		this.outType = outType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.PAYER_NAME
	 *
	 * @return the value of cw_money_operation.PAYER_NAME
	 *
	 * @mbggenerated
	 */
	public String getPayerName() {
		return payerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.PAYER_NAME
	 *
	 * @param payerName
	 *            the value for cw_money_operation.PAYER_NAME
	 *
	 * @mbggenerated
	 */
	public void setPayerName(String payerName) {
		this.payerName = payerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.PAYER_BANK_ID
	 *
	 * @return the value of cw_money_operation.PAYER_BANK_ID
	 *
	 * @mbggenerated
	 */
	public Integer getPayerBankId() {
		return payerBankId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.PAYER_BANK_ID
	 *
	 * @param payerBankId
	 *            the value for cw_money_operation.PAYER_BANK_ID
	 *
	 * @mbggenerated
	 */
	public void setPayerBankId(Integer payerBankId) {
		this.payerBankId = payerBankId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.PAYER_SUBBRANCH
	 *
	 * @return the value of cw_money_operation.PAYER_SUBBRANCH
	 *
	 * @mbggenerated
	 */
	public String getPayerSubbranch() {
		return payerSubbranch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.PAYER_SUBBRANCH
	 *
	 * @param payerSubbranch
	 *            the value for cw_money_operation.PAYER_SUBBRANCH
	 *
	 * @mbggenerated
	 */
	public void setPayerSubbranch(String payerSubbranch) {
		this.payerSubbranch = payerSubbranch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.PAYER_CARD_NO
	 *
	 * @return the value of cw_money_operation.PAYER_CARD_NO
	 *
	 * @mbggenerated
	 */
	public String getPayerCardNo() {
		return payerCardNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.PAYER_CARD_NO
	 *
	 * @param payerCardNo
	 *            the value for cw_money_operation.PAYER_CARD_NO
	 *
	 * @mbggenerated
	 */
	public void setPayerCardNo(String payerCardNo) {
		this.payerCardNo = payerCardNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.IN_BANK_ACCOUNT_ID
	 *
	 * @return the value of cw_money_operation.IN_BANK_ACCOUNT_ID
	 *
	 * @mbggenerated
	 */
	public Integer getInBankAccountId() {
		return inBankAccountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.IN_BANK_ACCOUNT_ID
	 *
	 * @param inBankAccountId
	 *            the value for cw_money_operation.IN_BANK_ACCOUNT_ID
	 *
	 * @mbggenerated
	 */
	public void setInBankAccountId(Integer inBankAccountId) {
		this.inBankAccountId = inBankAccountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.IN_TYPE
	 *
	 * @return the value of cw_money_operation.IN_TYPE
	 *
	 * @mbggenerated
	 */
	public Integer getInType() {
		return inType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.IN_TYPE
	 *
	 * @param inType
	 *            the value for cw_money_operation.IN_TYPE
	 *
	 * @mbggenerated
	 */
	public void setInType(Integer inType) {
		this.inType = inType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.PAYEE_NAME
	 *
	 * @return the value of cw_money_operation.PAYEE_NAME
	 *
	 * @mbggenerated
	 */
	public String getPayeeName() {
		return payeeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.PAYEE_NAME
	 *
	 * @param payeeName
	 *            the value for cw_money_operation.PAYEE_NAME
	 *
	 * @mbggenerated
	 */
	public void setPayeeName(String payeeName) {
		this.payeeName = payeeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.PAYEE_BANK_ID
	 *
	 * @return the value of cw_money_operation.PAYEE_BANK_ID
	 *
	 * @mbggenerated
	 */
	public Integer getPayeeBankId() {
		return payeeBankId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.PAYEE_BANK_ID
	 *
	 * @param payeeBankId
	 *            the value for cw_money_operation.PAYEE_BANK_ID
	 *
	 * @mbggenerated
	 */
	public void setPayeeBankId(Integer payeeBankId) {
		this.payeeBankId = payeeBankId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.PAYEE_SUBBRANCH
	 *
	 * @return the value of cw_money_operation.PAYEE_SUBBRANCH
	 *
	 * @mbggenerated
	 */
	public String getPayeeSubbranch() {
		return payeeSubbranch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.PAYEE_SUBBRANCH
	 *
	 * @param payeeSubbranch
	 *            the value for cw_money_operation.PAYEE_SUBBRANCH
	 *
	 * @mbggenerated
	 */
	public void setPayeeSubbranch(String payeeSubbranch) {
		this.payeeSubbranch = payeeSubbranch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.PAYEE_CARD_NO
	 *
	 * @return the value of cw_money_operation.PAYEE_CARD_NO
	 *
	 * @mbggenerated
	 */
	public String getPayeeCardNo() {
		return payeeCardNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.PAYEE_CARD_NO
	 *
	 * @param payeeCardNo
	 *            the value for cw_money_operation.PAYEE_CARD_NO
	 *
	 * @mbggenerated
	 */
	public void setPayeeCardNo(String payeeCardNo) {
		this.payeeCardNo = payeeCardNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.STATUS
	 *
	 * @return the value of cw_money_operation.STATUS
	 *
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.STATUS
	 *
	 * @param status
	 *            the value for cw_money_operation.STATUS
	 *
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.OPERATION_TYPE
	 *
	 * @return the value of cw_money_operation.OPERATION_TYPE
	 *
	 * @mbggenerated
	 */
	public Integer getOperationType() {
		return operationType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.OPERATION_TYPE
	 *
	 * @param operationType
	 *            the value for cw_money_operation.OPERATION_TYPE
	 *
	 * @mbggenerated
	 */
	public void setOperationType(Integer operationType) {
		this.operationType = operationType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.BUSINESS_TIME
	 *
	 * @return the value of cw_money_operation.BUSINESS_TIME
	 *
	 * @mbggenerated
	 */
	public Date getBusinessTime() {
		return businessTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.BUSINESS_TIME
	 *
	 * @param businessTime
	 *            the value for cw_money_operation.BUSINESS_TIME
	 *
	 * @mbggenerated
	 */
	public void setBusinessTime(Date businessTime) {
		this.businessTime = businessTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.REMARK
	 *
	 * @return the value of cw_money_operation.REMARK
	 *
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.REMARK
	 *
	 * @param remark
	 *            the value for cw_money_operation.REMARK
	 *
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.ADDUSER
	 *
	 * @return the value of cw_money_operation.ADDUSER
	 *
	 * @mbggenerated
	 */
	public Integer getAdduser() {
		return adduser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.ADDUSER
	 *
	 * @param adduser
	 *            the value for cw_money_operation.ADDUSER
	 *
	 * @mbggenerated
	 */
	public void setAdduser(Integer adduser) {
		this.adduser = adduser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.ADDTIME
	 *
	 * @return the value of cw_money_operation.ADDTIME
	 *
	 * @mbggenerated
	 */
	public Date getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.ADDTIME
	 *
	 * @param addtime
	 *            the value for cw_money_operation.ADDTIME
	 *
	 * @mbggenerated
	 */
	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.ADDIP
	 *
	 * @return the value of cw_money_operation.ADDIP
	 *
	 * @mbggenerated
	 */
	public String getAddip() {
		return addip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.ADDIP
	 *
	 * @param addip
	 *            the value for cw_money_operation.ADDIP
	 *
	 * @mbggenerated
	 */
	public void setAddip(String addip) {
		this.addip = addip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.UPDATEUSER
	 *
	 * @return the value of cw_money_operation.UPDATEUSER
	 *
	 * @mbggenerated
	 */
	public Integer getUpdateuser() {
		return updateuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.UPDATEUSER
	 *
	 * @param updateuser
	 *            the value for cw_money_operation.UPDATEUSER
	 *
	 * @mbggenerated
	 */
	public void setUpdateuser(Integer updateuser) {
		this.updateuser = updateuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.UPDATETIME
	 *
	 * @return the value of cw_money_operation.UPDATETIME
	 *
	 * @mbggenerated
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.UPDATETIME
	 *
	 * @param updatetime
	 *            the value for cw_money_operation.UPDATETIME
	 *
	 * @mbggenerated
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cw_money_operation.UPDATEIP
	 *
	 * @return the value of cw_money_operation.UPDATEIP
	 *
	 * @mbggenerated
	 */
	public String getUpdateip() {
		return updateip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cw_money_operation.UPDATEIP
	 *
	 * @param updateip
	 *            the value for cw_money_operation.UPDATEIP
	 *
	 * @mbggenerated
	 */
	public void setUpdateip(String updateip) {
		this.updateip = updateip;
	}
}