package com.cxdai.console.finance.virement.entity;

import java.util.Date;

public class MoneyOperationApprove {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_money_operation_approve.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_money_operation_approve.TARGET_ID
     *
     * @mbggenerated
     */
    private Integer targetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_money_operation_approve.TARGET_NAME
     *
     * @mbggenerated
     */
    private String targetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_money_operation_approve.TARGET_TYPE
     *
     * @mbggenerated
     */
    private Integer targetType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_money_operation_approve.BUSINESS_TIME
     *
     * @mbggenerated
     */
    private Date businessTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_money_operation_approve.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_money_operation_approve.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_money_operation_approve.ADDUSER
     *
     * @mbggenerated
     */
    private Integer adduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_money_operation_approve.ADDTIME
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cw_money_operation_approve.ADDIP
     *
     * @mbggenerated
     */
    private String addip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_money_operation_approve.id
     *
     * @return the value of cw_money_operation_approve.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_money_operation_approve.id
     *
     * @param id the value for cw_money_operation_approve.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_money_operation_approve.TARGET_ID
     *
     * @return the value of cw_money_operation_approve.TARGET_ID
     *
     * @mbggenerated
     */
    public Integer getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_money_operation_approve.TARGET_ID
     *
     * @param targetId the value for cw_money_operation_approve.TARGET_ID
     *
     * @mbggenerated
     */
    public void setTargetId(Integer targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_money_operation_approve.TARGET_NAME
     *
     * @return the value of cw_money_operation_approve.TARGET_NAME
     *
     * @mbggenerated
     */
    public String getTargetName() {
        return targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_money_operation_approve.TARGET_NAME
     *
     * @param targetName the value for cw_money_operation_approve.TARGET_NAME
     *
     * @mbggenerated
     */
    public void setTargetName(String targetName) {
        this.targetName = targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_money_operation_approve.TARGET_TYPE
     *
     * @return the value of cw_money_operation_approve.TARGET_TYPE
     *
     * @mbggenerated
     */
    public Integer getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_money_operation_approve.TARGET_TYPE
     *
     * @param targetType the value for cw_money_operation_approve.TARGET_TYPE
     *
     * @mbggenerated
     */
    public void setTargetType(Integer targetType) {
        this.targetType = targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_money_operation_approve.BUSINESS_TIME
     *
     * @return the value of cw_money_operation_approve.BUSINESS_TIME
     *
     * @mbggenerated
     */
    public Date getBusinessTime() {
        return businessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_money_operation_approve.BUSINESS_TIME
     *
     * @param businessTime the value for cw_money_operation_approve.BUSINESS_TIME
     *
     * @mbggenerated
     */
    public void setBusinessTime(Date businessTime) {
        this.businessTime = businessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_money_operation_approve.REMARK
     *
     * @return the value of cw_money_operation_approve.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_money_operation_approve.REMARK
     *
     * @param remark the value for cw_money_operation_approve.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_money_operation_approve.STATUS
     *
     * @return the value of cw_money_operation_approve.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_money_operation_approve.STATUS
     *
     * @param status the value for cw_money_operation_approve.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_money_operation_approve.ADDUSER
     *
     * @return the value of cw_money_operation_approve.ADDUSER
     *
     * @mbggenerated
     */
    public Integer getAdduser() {
        return adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_money_operation_approve.ADDUSER
     *
     * @param adduser the value for cw_money_operation_approve.ADDUSER
     *
     * @mbggenerated
     */
    public void setAdduser(Integer adduser) {
        this.adduser = adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_money_operation_approve.ADDTIME
     *
     * @return the value of cw_money_operation_approve.ADDTIME
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_money_operation_approve.ADDTIME
     *
     * @param addtime the value for cw_money_operation_approve.ADDTIME
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cw_money_operation_approve.ADDIP
     *
     * @return the value of cw_money_operation_approve.ADDIP
     *
     * @mbggenerated
     */
    public String getAddip() {
        return addip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cw_money_operation_approve.ADDIP
     *
     * @param addip the value for cw_money_operation_approve.ADDIP
     *
     * @mbggenerated
     */
    public void setAddip(String addip) {
        this.addip = addip;
    }
}