package com.cxdai.console.finance.virement.mapper;

import com.cxdai.console.finance.virement.entity.AttachMent;
import java.util.List;

public interface AttachMentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_attachment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_attachment
     *
     * @mbggenerated
     */
    int insert(AttachMent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_attachment
     *
     * @mbggenerated
     */
    AttachMent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_attachment
     *
     * @mbggenerated
     */
    List<AttachMent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_attachment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AttachMent record);
    
    List<AttachMent> selectFielByTagleId(AttachMent attachMent);
    
}