package com.cxdai.console.finance.virement.mapper;

import com.cxdai.console.finance.virement.entity.BankAccountInfo;
import java.util.List;

public interface BankAccountInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_bank_account_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_bank_account_info
     *
     * @mbggenerated
     */
    int insert(BankAccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_bank_account_info
     *
     * @mbggenerated
     */
    BankAccountInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_bank_account_info
     *
     * @mbggenerated
     */
    List<BankAccountInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_bank_account_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BankAccountInfo record);
}