package com.cxdai.console.finance.virement.mapper;

import com.cxdai.console.common.page.Page;
import com.cxdai.console.finance.virement.entity.CheckWithdrawals;
import com.cxdai.console.finance.virement.vo.QueryPageCheckWithCnd;
import com.cxdai.console.finance.virement.vo.UpdateCheckWithCnd;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CheckWithdrawalsMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cw_check_withdrawals
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cw_check_withdrawals
	 *
	 * @mbggenerated
	 */
	int insert(CheckWithdrawals record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cw_check_withdrawals
	 *
	 * @mbggenerated
	 */
	CheckWithdrawals selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cw_check_withdrawals
	 *
	 * @mbggenerated
	 */
	List<CheckWithdrawals> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cw_check_withdrawals
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CheckWithdrawals record);

	/**
	 * 分页查询提现对账列表
	 * 
	 * @param request
	 * @return
	 */
	Integer queryPageCheckWithCount(QueryPageCheckWithCnd request);

	List<CheckWithdrawals> queryPageCheckWithdrawals(QueryPageCheckWithCnd request, Page page);

	/**
	 * 对账操作,通过ID变更对账信息
	 * 
	 * @param requestCnd
	 */
	int updateCheckWithById(UpdateCheckWithCnd requestCnd);

	CheckWithdrawals selectByPrimaryKeyForUpdate(@Param("id") Integer id);

	int updateWithdrawal(CheckWithdrawals checkWithdrawals);
}