package com.cxdai.console.finance.virement.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.cxdai.console.common.page.Page;
import com.cxdai.console.finance.virement.entity.Journal;
import com.cxdai.console.finance.virement.vo.JournalCnd;
import com.cxdai.console.finance.virement.vo.JournalVo;

public interface JournalMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cw_journal
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cw_journal
	 *
	 * @mbggenerated
	 */
	int insert(Journal record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cw_journal
	 *
	 * @mbggenerated
	 */
	Journal selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cw_journal
	 *
	 * @mbggenerated
	 */
	List<Journal> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table cw_journal
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Journal record);

	/****
	 * 根据条件统计日记账总数
	 * 
	 * @param journalCnd
	 * @return
	 */
	Integer queryListCountByCnd(JournalCnd journalCnd);

	/****
	 * 根据条件查询日记账列表
	 * 
	 * @param journalCnd
	 * @param page
	 * @return
	 */
	List<JournalVo> queryListByCnd(JournalCnd journalCnd, Page page);

	/****
	 * 查找正常状态下最新的一条现金日记账
	 * 
	 * @return
	 */
	JournalVo selectMaxJournal(JournalVo journalVo);

	/***
	 * 查询正常状态下当前ID前一条记录
	 * 
	 * @param id
	 * @return
	 */
	JournalVo selectPreOneJournal(JournalVo journalVo);

	Journal selectJournalForUpdate(@Param("id") Integer id);

	int deleteJournal(Journal journal);

	/***
	 * 查询导出现金日记账集合
	 * 
	 * @param journalCnd
	 * @return
	 */
	List<Map<String, Object>> findJournalList(JournalCnd journalCnd);

	/****
	 * 根据时间查询操作日期当天该时间以后的所有正常状态下的现金日记账
	 * 
	 * @param journalVo
	 * @return
	 */
	List<Journal> selectAfterCurrentOperationDateThisDay(JournalVo journalVo);

}