package com.cxdai.console.finance.virement.mapper;

import com.cxdai.console.finance.virement.entity.MoneyOperationApprove;
import java.util.List;

public interface MoneyOperationApproveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_money_operation_approve
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_money_operation_approve
     *
     * @mbggenerated
     */
    int insert(MoneyOperationApprove record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_money_operation_approve
     *
     * @mbggenerated
     */
    MoneyOperationApprove selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_money_operation_approve
     *
     * @mbggenerated
     */
    List<MoneyOperationApprove> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cw_money_operation_approve
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MoneyOperationApprove record);
}