package com.cxdai.console.borrow.check.entity;

import java.math.BigDecimal;
import java.util.Date;

public class BorrowerDealError {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrower_deal_error.id
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrower_deal_error.status
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrower_deal_error.borrow_id
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    private Integer borrowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrower_deal_error.P2PID
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    private String p2pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrower_deal_error.serialNo
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    private String serialno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrower_deal_error.ACCOUNT
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    private BigDecimal account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrower_deal_error.fee
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrower_deal_error.tradetime
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    private Date tradetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrower_deal_error.addtime
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrower_deal_error.updtime
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    private Date updtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrower_deal_error.updateUser
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    private Integer updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrower_deal_error.addUser
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    private Integer adduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrower_deal_error.dispose_status
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    private Integer disposeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrower_deal_error.remark
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    private String remark;
    
    private String checkRemark;
    
    private String oriSerialNo;
    
    private Integer userId;
    
    
    
    

    public String getOriSerialNo() {
		return oriSerialNo;
	}

	public void setOriSerialNo(String oriSerialNo) {
		this.oriSerialNo = oriSerialNo;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getCheckRemark() {
		return checkRemark;
	}

	public void setCheckRemark(String checkRemark) {
		this.checkRemark = checkRemark;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrower_deal_error.id
     *
     * @return the value of t_borrower_deal_error.id
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrower_deal_error.id
     *
     * @param id the value for t_borrower_deal_error.id
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrower_deal_error.status
     *
     * @return the value of t_borrower_deal_error.status
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrower_deal_error.status
     *
     * @param status the value for t_borrower_deal_error.status
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrower_deal_error.borrow_id
     *
     * @return the value of t_borrower_deal_error.borrow_id
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public Integer getBorrowId() {
        return borrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrower_deal_error.borrow_id
     *
     * @param borrowId the value for t_borrower_deal_error.borrow_id
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public void setBorrowId(Integer borrowId) {
        this.borrowId = borrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrower_deal_error.P2PID
     *
     * @return the value of t_borrower_deal_error.P2PID
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public String getP2pid() {
        return p2pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrower_deal_error.P2PID
     *
     * @param p2pid the value for t_borrower_deal_error.P2PID
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public void setP2pid(String p2pid) {
        this.p2pid = p2pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrower_deal_error.serialNo
     *
     * @return the value of t_borrower_deal_error.serialNo
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public String getSerialno() {
        return serialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrower_deal_error.serialNo
     *
     * @param serialno the value for t_borrower_deal_error.serialNo
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public void setSerialno(String serialno) {
        this.serialno = serialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrower_deal_error.ACCOUNT
     *
     * @return the value of t_borrower_deal_error.ACCOUNT
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public BigDecimal getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrower_deal_error.ACCOUNT
     *
     * @param account the value for t_borrower_deal_error.ACCOUNT
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public void setAccount(BigDecimal account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrower_deal_error.fee
     *
     * @return the value of t_borrower_deal_error.fee
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrower_deal_error.fee
     *
     * @param fee the value for t_borrower_deal_error.fee
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrower_deal_error.tradetime
     *
     * @return the value of t_borrower_deal_error.tradetime
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public Date getTradetime() {
        return tradetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrower_deal_error.tradetime
     *
     * @param tradetime the value for t_borrower_deal_error.tradetime
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public void setTradetime(Date tradetime) {
        this.tradetime = tradetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrower_deal_error.addtime
     *
     * @return the value of t_borrower_deal_error.addtime
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrower_deal_error.addtime
     *
     * @param addtime the value for t_borrower_deal_error.addtime
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrower_deal_error.updtime
     *
     * @return the value of t_borrower_deal_error.updtime
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public Date getUpdtime() {
        return updtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrower_deal_error.updtime
     *
     * @param updtime the value for t_borrower_deal_error.updtime
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public void setUpdtime(Date updtime) {
        this.updtime = updtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrower_deal_error.updateUser
     *
     * @return the value of t_borrower_deal_error.updateUser
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public Integer getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrower_deal_error.updateUser
     *
     * @param updateuser the value for t_borrower_deal_error.updateUser
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public void setUpdateuser(Integer updateuser) {
        this.updateuser = updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrower_deal_error.addUser
     *
     * @return the value of t_borrower_deal_error.addUser
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public Integer getAdduser() {
        return adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrower_deal_error.addUser
     *
     * @param adduser the value for t_borrower_deal_error.addUser
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public void setAdduser(Integer adduser) {
        this.adduser = adduser;
    }

  
    

    public Integer getDisposeStatus() {
		return disposeStatus;
	}

	public void setDisposeStatus(Integer disposeStatus) {
		this.disposeStatus = disposeStatus;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrower_deal_error.remark
     *
     * @return the value of t_borrower_deal_error.remark
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrower_deal_error.remark
     *
     * @param remark the value for t_borrower_deal_error.remark
     *
     * @mbggenerated Thu Jun 02 11:02:46 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}