package com.cxdai.console.customer.information.entity;

import java.util.Date;

public class BorrowerUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrower_user.ID
     *
     * @mbggenerated Mon May 16 10:46:18 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrower_user.USER_ID
     *
     * @mbggenerated Mon May 16 10:46:18 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrower_user.RepayName
     *
     * @mbggenerated Mon May 16 10:46:18 CST 2016
     */
    private String repayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrower_user.RepayAcct
     *
     * @mbggenerated Mon May 16 10:46:18 CST 2016
     */
    private String repayAcct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrower_user.STATUS
     *
     * @mbggenerated Mon May 16 10:46:18 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrower_user.REMARK
     *
     * @mbggenerated Mon May 16 10:46:18 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrower_user.ADDTIME
     *
     * @mbggenerated Mon May 16 10:46:18 CST 2016
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrower_user.ADDUSER
     *
     * @mbggenerated Mon May 16 10:46:18 CST 2016
     */
    private String adduser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrower_user.ID
     *
     * @return the value of t_borrower_user.ID
     *
     * @mbggenerated Mon May 16 10:46:18 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrower_user.ID
     *
     * @param id the value for t_borrower_user.ID
     *
     * @mbggenerated Mon May 16 10:46:18 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrower_user.USER_ID
     *
     * @return the value of t_borrower_user.USER_ID
     *
     * @mbggenerated Mon May 16 10:46:18 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrower_user.USER_ID
     *
     * @param userId the value for t_borrower_user.USER_ID
     *
     * @mbggenerated Mon May 16 10:46:18 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

   

    public String getRepayName() {
		return repayName;
	}

	public void setRepayName(String repayName) {
		this.repayName = repayName;
	}

	public String getRepayAcct() {
		return repayAcct;
	}

	public void setRepayAcct(String repayAcct) {
		this.repayAcct = repayAcct;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrower_user.STATUS
     *
     * @return the value of t_borrower_user.STATUS
     *
     * @mbggenerated Mon May 16 10:46:18 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrower_user.STATUS
     *
     * @param status the value for t_borrower_user.STATUS
     *
     * @mbggenerated Mon May 16 10:46:18 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrower_user.REMARK
     *
     * @return the value of t_borrower_user.REMARK
     *
     * @mbggenerated Mon May 16 10:46:18 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrower_user.REMARK
     *
     * @param remark the value for t_borrower_user.REMARK
     *
     * @mbggenerated Mon May 16 10:46:18 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrower_user.ADDTIME
     *
     * @return the value of t_borrower_user.ADDTIME
     *
     * @mbggenerated Mon May 16 10:46:18 CST 2016
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrower_user.ADDTIME
     *
     * @param addtime the value for t_borrower_user.ADDTIME
     *
     * @mbggenerated Mon May 16 10:46:18 CST 2016
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrower_user.ADDUSER
     *
     * @return the value of t_borrower_user.ADDUSER
     *
     * @mbggenerated Mon May 16 10:46:18 CST 2016
     */
    public String getAdduser() {
        return adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrower_user.ADDUSER
     *
     * @param adduser the value for t_borrower_user.ADDUSER
     *
     * @mbggenerated Mon May 16 10:46:18 CST 2016
     */
    public void setAdduser(String adduser) {
        this.adduser = adduser;
    }
}