package com.cxdai.console.cgnotify.mapper;

import org.apache.ibatis.annotations.Param;

import com.cxdai.console.cgnotify.entity.EReconHeader;

import java.util.Map;

public interface EReconHeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_header
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    int deleteByFilename(String filename);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_header
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    int insert(EReconHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_header
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    int insertSelective(EReconHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_header
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    EReconHeader selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_header
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    int updateByPrimaryKeySelective(EReconHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_header
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    int updateByPrimaryKey(EReconHeader record);
    
    EReconHeader findReconHeader(@Param("targetId")String targetId,@Param("targetType") Integer targetType);

    public EReconHeader queryRecon(@Param("targetType")Integer targetType,
                                   @Param("targetId") String targetId,
                                   @Param("fileName") String fileName);
}