package com.cxdai.console.cgnotify.mapper;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import com.cxdai.console.cgnotify.vo.ReconResultCnd;
import org.apache.ibatis.annotations.Param;

import com.cxdai.console.cgnotify.entity.EReconDetail;

public interface EReconDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_detail
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    int deleteByFilename(String filename);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_detail
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    int insert(EReconDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_detail
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    int insertSelective(EReconDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_detail
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    EReconDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_detail
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    int updateByPrimaryKeySelective(EReconDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_detail
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    int updateByPrimaryKey(EReconDetail record);
    
    List<EReconDetail> findReconDetail(@Param("targetId")String targetId,@Param("targetType") Integer targetType);
    
    BigDecimal findReconDetailMoney(@Param("targetId")String targetId,@Param("targetType") Integer targetType);

    public List<String> queryDetailP2PNoList(@Param("targetType") Integer targetType,
                                             @Param("targetId")String targetId,
                                             @Param("fileName") String fileName,
                                             @Param("status") Integer status);

    public EReconDetail queryDetail(@Param("targetType") Integer targetType,
                                             @Param("targetId")String targetId,
                                             @Param("fileName") String fileName,
                                             @Param("status") Integer status,
                                             @Param("p2pNo") String p2pNo);

    public EReconDetail queryOneDetail(@Param("targetType") Integer targetType,
                                    @Param("targetId")String targetId,
                                    @Param("fileName") String fileName);

    public BigDecimal queryDetailMoney(@Param("p2pNo")String p2pNo);

    Map<String, Object> sumReconDetailByCnd(ReconResultCnd reconResultCnd);

    Map<String,Object> sumTenderRecordByCnd(ReconResultCnd reconResultCnd);
}