package com.cxdai.console.cgnotify.mapper;

import com.cxdai.console.cgnotify.entity.EReconHeaderResult;
import com.cxdai.console.cgnotify.vo.EReconHeaderVo;

public interface EReconHeaderResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_header_result
     *
     * @mbggenerated Thu May 26 10:06:15 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    int deleteByFilename(String filename);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_header_result
     *
     * @mbggenerated Thu May 26 10:06:15 CST 2016
     */
    int insert(EReconHeaderResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_header_result
     *
     * @mbggenerated Thu May 26 10:06:15 CST 2016
     */
    int insertSelective(EReconHeaderResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_header_result
     *
     * @mbggenerated Thu May 26 10:06:15 CST 2016
     */
    EReconHeaderResult selectByPrimaryKey(Integer id);

    EReconHeaderVo sumBTFHeader(String projectId);

    EReconHeaderVo sumBRFHeader(String projectId);

    EReconHeaderVo queryBorrowHeader(String projectId);

    EReconHeaderVo queryHeader(String filename);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_header_result
     *
     * @mbggenerated Thu May 26 10:06:15 CST 2016
     */
    int updateByPrimaryKeySelective(EReconHeaderResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_header_result
     *
     * @mbggenerated Thu May 26 10:06:15 CST 2016
     */
    int updateByPrimaryKey(EReconHeaderResult record);
}