package com.cxdai.console.cgnotify.mapper;

import com.cxdai.console.cgnotify.entity.EReconFile;
import com.cxdai.console.cgnotify.vo.ReconCnd;
import com.cxdai.console.common.page.Page;

import java.util.List;

public interface EReconFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_file
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_file
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    int insert(EReconFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_file
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    int insertSelective(EReconFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_file
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    EReconFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_file
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    int updateByPrimaryKeySelective(EReconFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_file
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    int updateByPrimaryKey(EReconFile record);


    Integer queryListCountByCnd(ReconCnd reconCnd);

    List<EReconFile> queryListByCnd(ReconCnd reconCnd, Page page);

    public List<EReconFile> selectByFilename(String filename);
}