package com.cxdai.console.cgnotify.mapper;

import com.cxdai.console.cgnotify.entity.EReconDetailResult;
import com.cxdai.console.cgnotify.vo.EReconResultVo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EReconDetailResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_detail_result
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    int deleteByFilename(String filename);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_detail_result
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    int insert(EReconDetailResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_detail_result
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    int insertSelective(EReconDetailResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_detail_result
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    EReconDetailResult selectByPrimaryKey(Integer id);

    List<EReconResultVo> queryBTFDetail(@Param("borrowId") Integer borrowId,
                                        @Param("filename") String filename);

    List<EReconResultVo> queryBRFDetail(@Param("borrowId") Integer borrowId,
                                        @Param("filename") String filename);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_detail_result
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    int updateByPrimaryKeySelective(EReconDetailResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_recon_detail_result
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    int updateByPrimaryKey(EReconDetailResult record);
}