package com.cxdai.console.base.entity;

import java.util.Date;

public class BaseEBankInfoLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_bankinfo_log.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_bankinfo_log.EBANKINFO_ID
     *
     * @mbggenerated
     */
    private Integer ebankinfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_bankinfo_log.USER_ID
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_bankinfo_log.BANKNAME
     *
     * @mbggenerated
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_bankinfo_log.ECARD_NO
     *
     * @mbggenerated
     */
    private String ecardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_bankinfo_log.REALNAME
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_bankinfo_log.CERTTYPE
     *
     * @mbggenerated
     */
    private Integer certtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_bankinfo_log.CERT_NO
     *
     * @mbggenerated
     */
    private String certNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_bankinfo_log.MOBILE
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_bankinfo_log.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_bankinfo_log.BIND_NO
     *
     * @mbggenerated
     */
    private String bindNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_bankinfo_log.CARDTYPE
     *
     * @mbggenerated
     */
    private Integer cardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_bankinfo_log.CUSTODY_BIND_NO
     *
     * @mbggenerated
     */
    private String custodyBindNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_bankinfo_log.CUSTODY_BIND_NAME
     *
     * @mbggenerated
     */
    private String custodyBindName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_bankinfo_log.ADDTIME
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_bankinfo_log.ID
     *
     * @return the value of e_bankinfo_log.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_bankinfo_log.ID
     *
     * @param id the value for e_bankinfo_log.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_bankinfo_log.EBANKINFO_ID
     *
     * @return the value of e_bankinfo_log.EBANKINFO_ID
     *
     * @mbggenerated
     */
    public Integer getEbankinfoId() {
        return ebankinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_bankinfo_log.EBANKINFO_ID
     *
     * @param ebankinfoId the value for e_bankinfo_log.EBANKINFO_ID
     *
     * @mbggenerated
     */
    public void setEbankinfoId(Integer ebankinfoId) {
        this.ebankinfoId = ebankinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_bankinfo_log.USER_ID
     *
     * @return the value of e_bankinfo_log.USER_ID
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_bankinfo_log.USER_ID
     *
     * @param userId the value for e_bankinfo_log.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_bankinfo_log.BANKNAME
     *
     * @return the value of e_bankinfo_log.BANKNAME
     *
     * @mbggenerated
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_bankinfo_log.BANKNAME
     *
     * @param bankname the value for e_bankinfo_log.BANKNAME
     *
     * @mbggenerated
     */
    public void setBankname(String bankname) {
        this.bankname = bankname == null ? null : bankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_bankinfo_log.ECARD_NO
     *
     * @return the value of e_bankinfo_log.ECARD_NO
     *
     * @mbggenerated
     */
    public String getEcardNo() {
        return ecardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_bankinfo_log.ECARD_NO
     *
     * @param ecardNo the value for e_bankinfo_log.ECARD_NO
     *
     * @mbggenerated
     */
    public void setEcardNo(String ecardNo) {
        this.ecardNo = ecardNo == null ? null : ecardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_bankinfo_log.REALNAME
     *
     * @return the value of e_bankinfo_log.REALNAME
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_bankinfo_log.REALNAME
     *
     * @param realname the value for e_bankinfo_log.REALNAME
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_bankinfo_log.CERTTYPE
     *
     * @return the value of e_bankinfo_log.CERTTYPE
     *
     * @mbggenerated
     */
    public Integer getCerttype() {
        return certtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_bankinfo_log.CERTTYPE
     *
     * @param certtype the value for e_bankinfo_log.CERTTYPE
     *
     * @mbggenerated
     */
    public void setCerttype(Integer certtype) {
        this.certtype = certtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_bankinfo_log.CERT_NO
     *
     * @return the value of e_bankinfo_log.CERT_NO
     *
     * @mbggenerated
     */
    public String getCertNo() {
        return certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_bankinfo_log.CERT_NO
     *
     * @param certNo the value for e_bankinfo_log.CERT_NO
     *
     * @mbggenerated
     */
    public void setCertNo(String certNo) {
        this.certNo = certNo == null ? null : certNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_bankinfo_log.MOBILE
     *
     * @return the value of e_bankinfo_log.MOBILE
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_bankinfo_log.MOBILE
     *
     * @param mobile the value for e_bankinfo_log.MOBILE
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_bankinfo_log.STATUS
     *
     * @return the value of e_bankinfo_log.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_bankinfo_log.STATUS
     *
     * @param status the value for e_bankinfo_log.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_bankinfo_log.BIND_NO
     *
     * @return the value of e_bankinfo_log.BIND_NO
     *
     * @mbggenerated
     */
    public String getBindNo() {
        return bindNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_bankinfo_log.BIND_NO
     *
     * @param bindNo the value for e_bankinfo_log.BIND_NO
     *
     * @mbggenerated
     */
    public void setBindNo(String bindNo) {
        this.bindNo = bindNo == null ? null : bindNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_bankinfo_log.CARDTYPE
     *
     * @return the value of e_bankinfo_log.CARDTYPE
     *
     * @mbggenerated
     */
    public Integer getCardtype() {
        return cardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_bankinfo_log.CARDTYPE
     *
     * @param cardtype the value for e_bankinfo_log.CARDTYPE
     *
     * @mbggenerated
     */
    public void setCardtype(Integer cardtype) {
        this.cardtype = cardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_bankinfo_log.CUSTODY_BIND_NO
     *
     * @return the value of e_bankinfo_log.CUSTODY_BIND_NO
     *
     * @mbggenerated
     */
    public String getCustodyBindNo() {
        return custodyBindNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_bankinfo_log.CUSTODY_BIND_NO
     *
     * @param custodyBindNo the value for e_bankinfo_log.CUSTODY_BIND_NO
     *
     * @mbggenerated
     */
    public void setCustodyBindNo(String custodyBindNo) {
        this.custodyBindNo = custodyBindNo == null ? null : custodyBindNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_bankinfo_log.CUSTODY_BIND_NAME
     *
     * @return the value of e_bankinfo_log.CUSTODY_BIND_NAME
     *
     * @mbggenerated
     */
    public String getCustodyBindName() {
        return custodyBindName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_bankinfo_log.CUSTODY_BIND_NAME
     *
     * @param custodyBindName the value for e_bankinfo_log.CUSTODY_BIND_NAME
     *
     * @mbggenerated
     */
    public void setCustodyBindName(String custodyBindName) {
        this.custodyBindName = custodyBindName == null ? null : custodyBindName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_bankinfo_log.ADDTIME
     *
     * @return the value of e_bankinfo_log.ADDTIME
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_bankinfo_log.ADDTIME
     *
     * @param addtime the value for e_bankinfo_log.ADDTIME
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}