package com.cxdai.console.cgnotify.entity;

import java.util.Date;

public class EReconDetailResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail_result.ID
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail_result.HEADER_ID
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    private Integer headerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail_result.DETAIL_ID
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    private Integer detailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail_result.TARGET_TYPE
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    private Integer targetType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail_result.TARGET_ID
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    private String targetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail_result.TARGET_NAME
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    private String targetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail_result.SYS_VALUE
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    private String sysValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail_result.BANK_VALUE
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    private String bankValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail_result.RESULT
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    private Integer result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail_result.ADDUSER
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    private Integer adduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail_result.ADDTIME
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail_result.REMARK
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail_result.FILE_NAME
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    private String fileName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail_result.ID
     *
     * @return the value of e_recon_detail_result.ID
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail_result.ID
     *
     * @param id the value for e_recon_detail_result.ID
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail_result.HEADER_ID
     *
     * @return the value of e_recon_detail_result.HEADER_ID
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public Integer getHeaderId() {
        return headerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail_result.HEADER_ID
     *
     * @param headerId the value for e_recon_detail_result.HEADER_ID
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public void setHeaderId(Integer headerId) {
        this.headerId = headerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail_result.DETAIL_ID
     *
     * @return the value of e_recon_detail_result.DETAIL_ID
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public Integer getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail_result.DETAIL_ID
     *
     * @param detailId the value for e_recon_detail_result.DETAIL_ID
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public void setDetailId(Integer detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail_result.TARGET_TYPE
     *
     * @return the value of e_recon_detail_result.TARGET_TYPE
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public Integer getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail_result.TARGET_TYPE
     *
     * @param targetType the value for e_recon_detail_result.TARGET_TYPE
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public void setTargetType(Integer targetType) {
        this.targetType = targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail_result.TARGET_ID
     *
     * @return the value of e_recon_detail_result.TARGET_ID
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public String getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail_result.TARGET_ID
     *
     * @param targetId the value for e_recon_detail_result.TARGET_ID
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public void setTargetId(String targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail_result.TARGET_NAME
     *
     * @return the value of e_recon_detail_result.TARGET_NAME
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public String getTargetName() {
        return targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail_result.TARGET_NAME
     *
     * @param targetName the value for e_recon_detail_result.TARGET_NAME
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public void setTargetName(String targetName) {
        this.targetName = targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail_result.SYS_VALUE
     *
     * @return the value of e_recon_detail_result.SYS_VALUE
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public String getSysValue() {
        return sysValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail_result.SYS_VALUE
     *
     * @param sysValue the value for e_recon_detail_result.SYS_VALUE
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public void setSysValue(String sysValue) {
        this.sysValue = sysValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail_result.BANK_VALUE
     *
     * @return the value of e_recon_detail_result.BANK_VALUE
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public String getBankValue() {
        return bankValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail_result.BANK_VALUE
     *
     * @param bankValue the value for e_recon_detail_result.BANK_VALUE
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public void setBankValue(String bankValue) {
        this.bankValue = bankValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail_result.RESULT
     *
     * @return the value of e_recon_detail_result.RESULT
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail_result.RESULT
     *
     * @param result the value for e_recon_detail_result.RESULT
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public void setResult(Integer result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail_result.ADDUSER
     *
     * @return the value of e_recon_detail_result.ADDUSER
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public Integer getAdduser() {
        return adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail_result.ADDUSER
     *
     * @param adduser the value for e_recon_detail_result.ADDUSER
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public void setAdduser(Integer adduser) {
        this.adduser = adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail_result.ADDTIME
     *
     * @return the value of e_recon_detail_result.ADDTIME
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail_result.ADDTIME
     *
     * @param addtime the value for e_recon_detail_result.ADDTIME
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail_result.REMARK
     *
     * @return the value of e_recon_detail_result.REMARK
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail_result.REMARK
     *
     * @param remark the value for e_recon_detail_result.REMARK
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail_result.FILE_NAME
     *
     * @return the value of e_recon_detail_result.FILE_NAME
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail_result.FILE_NAME
     *
     * @param fileName the value for e_recon_detail_result.FILE_NAME
     *
     * @mbggenerated Thu May 26 10:04:10 CST 2016
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
}