package com.cxdai.console.cgnotify.entity;

import java.math.BigDecimal;
import java.util.Date;

public class EReconDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail.ID
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail.HEADER_ID
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    private Integer headerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail.TARGET_TYPE
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    private Integer targetType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail.TARGET_ID
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    private String targetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail.TARGET_NAME
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    private String targetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail.P2P_NO
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    private String p2pNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail.BANK_NO
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    private String bankNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail.STATUS
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail.TRADETIME
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    private Date tradetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail.MONEY
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail.MONEY2
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    private BigDecimal money2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail.FEE
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail.STATUS2
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    private Integer status2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail.STATUS3
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    private Integer status3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail.EXP_TYPE
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    private Integer expType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail.EXP1
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    private String exp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail.EXP2
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    private String exp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail.ADDUSER
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    private Integer adduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail.ADDTIME
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail.REMARK
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_detail.FILE_NAME
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    private String fileName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail.ID
     *
     * @return the value of e_recon_detail.ID
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail.ID
     *
     * @param id the value for e_recon_detail.ID
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail.HEADER_ID
     *
     * @return the value of e_recon_detail.HEADER_ID
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public Integer getHeaderId() {
        return headerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail.HEADER_ID
     *
     * @param headerId the value for e_recon_detail.HEADER_ID
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public void setHeaderId(Integer headerId) {
        this.headerId = headerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail.TARGET_TYPE
     *
     * @return the value of e_recon_detail.TARGET_TYPE
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public Integer getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail.TARGET_TYPE
     *
     * @param targetType the value for e_recon_detail.TARGET_TYPE
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public void setTargetType(Integer targetType) {
        this.targetType = targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail.TARGET_ID
     *
     * @return the value of e_recon_detail.TARGET_ID
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public String getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail.TARGET_ID
     *
     * @param targetId the value for e_recon_detail.TARGET_ID
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public void setTargetId(String targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail.TARGET_NAME
     *
     * @return the value of e_recon_detail.TARGET_NAME
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public String getTargetName() {
        return targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail.TARGET_NAME
     *
     * @param targetName the value for e_recon_detail.TARGET_NAME
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public void setTargetName(String targetName) {
        this.targetName = targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail.P2P_NO
     *
     * @return the value of e_recon_detail.P2P_NO
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public String getP2pNo() {
        return p2pNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail.P2P_NO
     *
     * @param p2pNo the value for e_recon_detail.P2P_NO
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public void setP2pNo(String p2pNo) {
        this.p2pNo = p2pNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail.BANK_NO
     *
     * @return the value of e_recon_detail.BANK_NO
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail.BANK_NO
     *
     * @param bankNo the value for e_recon_detail.BANK_NO
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail.STATUS
     *
     * @return the value of e_recon_detail.STATUS
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail.STATUS
     *
     * @param status the value for e_recon_detail.STATUS
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail.TRADETIME
     *
     * @return the value of e_recon_detail.TRADETIME
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public Date getTradetime() {
        return tradetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail.TRADETIME
     *
     * @param tradetime the value for e_recon_detail.TRADETIME
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public void setTradetime(Date tradetime) {
        this.tradetime = tradetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail.MONEY
     *
     * @return the value of e_recon_detail.MONEY
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail.MONEY
     *
     * @param money the value for e_recon_detail.MONEY
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail.MONEY2
     *
     * @return the value of e_recon_detail.MONEY2
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public BigDecimal getMoney2() {
        return money2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail.MONEY2
     *
     * @param money2 the value for e_recon_detail.MONEY2
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public void setMoney2(BigDecimal money2) {
        this.money2 = money2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail.FEE
     *
     * @return the value of e_recon_detail.FEE
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail.FEE
     *
     * @param fee the value for e_recon_detail.FEE
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail.STATUS2
     *
     * @return the value of e_recon_detail.STATUS2
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public Integer getStatus2() {
        return status2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail.STATUS2
     *
     * @param status2 the value for e_recon_detail.STATUS2
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public void setStatus2(Integer status2) {
        this.status2 = status2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail.STATUS3
     *
     * @return the value of e_recon_detail.STATUS3
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public Integer getStatus3() {
        return status3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail.STATUS3
     *
     * @param status3 the value for e_recon_detail.STATUS3
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public void setStatus3(Integer status3) {
        this.status3 = status3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail.EXP_TYPE
     *
     * @return the value of e_recon_detail.EXP_TYPE
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public Integer getExpType() {
        return expType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail.EXP_TYPE
     *
     * @param expType the value for e_recon_detail.EXP_TYPE
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public void setExpType(Integer expType) {
        this.expType = expType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail.EXP1
     *
     * @return the value of e_recon_detail.EXP1
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public String getExp1() {
        return exp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail.EXP1
     *
     * @param exp1 the value for e_recon_detail.EXP1
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public void setExp1(String exp1) {
        this.exp1 = exp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail.EXP2
     *
     * @return the value of e_recon_detail.EXP2
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public String getExp2() {
        return exp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail.EXP2
     *
     * @param exp2 the value for e_recon_detail.EXP2
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public void setExp2(String exp2) {
        this.exp2 = exp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail.ADDUSER
     *
     * @return the value of e_recon_detail.ADDUSER
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public Integer getAdduser() {
        return adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail.ADDUSER
     *
     * @param adduser the value for e_recon_detail.ADDUSER
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public void setAdduser(Integer adduser) {
        this.adduser = adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail.ADDTIME
     *
     * @return the value of e_recon_detail.ADDTIME
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail.ADDTIME
     *
     * @param addtime the value for e_recon_detail.ADDTIME
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail.REMARK
     *
     * @return the value of e_recon_detail.REMARK
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail.REMARK
     *
     * @param remark the value for e_recon_detail.REMARK
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_detail.FILE_NAME
     *
     * @return the value of e_recon_detail.FILE_NAME
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_detail.FILE_NAME
     *
     * @param fileName the value for e_recon_detail.FILE_NAME
     *
     * @mbggenerated Thu May 26 10:02:28 CST 2016
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
}