package com.cxdai.console.cgnotify.entity;

import java.util.Date;

public class EReconFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_file.ID
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_file.TARGET_TYPE
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    private Integer targetType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_file.TARGET_ID
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    private String targetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_file.TARGET_NAME
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    private String targetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_file.STATUS
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_file.ADDUSER
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    private Integer adduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_file.ADDTIME
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_file.REMARK
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_file.FILE_NAME
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    private String fileName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_file.ID
     *
     * @return the value of e_recon_file.ID
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_file.ID
     *
     * @param id the value for e_recon_file.ID
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_file.TARGET_TYPE
     *
     * @return the value of e_recon_file.TARGET_TYPE
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    public Integer getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_file.TARGET_TYPE
     *
     * @param targetType the value for e_recon_file.TARGET_TYPE
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    public void setTargetType(Integer targetType) {
        this.targetType = targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_file.TARGET_ID
     *
     * @return the value of e_recon_file.TARGET_ID
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    public String getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_file.TARGET_ID
     *
     * @param targetId the value for e_recon_file.TARGET_ID
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    public void setTargetId(String targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_file.TARGET_NAME
     *
     * @return the value of e_recon_file.TARGET_NAME
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    public String getTargetName() {
        return targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_file.TARGET_NAME
     *
     * @param targetName the value for e_recon_file.TARGET_NAME
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    public void setTargetName(String targetName) {
        this.targetName = targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_file.STATUS
     *
     * @return the value of e_recon_file.STATUS
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_file.STATUS
     *
     * @param status the value for e_recon_file.STATUS
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_file.ADDUSER
     *
     * @return the value of e_recon_file.ADDUSER
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    public Integer getAdduser() {
        return adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_file.ADDUSER
     *
     * @param adduser the value for e_recon_file.ADDUSER
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    public void setAdduser(Integer adduser) {
        this.adduser = adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_file.ADDTIME
     *
     * @return the value of e_recon_file.ADDTIME
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_file.ADDTIME
     *
     * @param addtime the value for e_recon_file.ADDTIME
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_file.REMARK
     *
     * @return the value of e_recon_file.REMARK
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_file.REMARK
     *
     * @param remark the value for e_recon_file.REMARK
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_file.FILE_NAME
     *
     * @return the value of e_recon_file.FILE_NAME
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_file.FILE_NAME
     *
     * @param fileName the value for e_recon_file.FILE_NAME
     *
     * @mbggenerated Thu May 26 10:05:18 CST 2016
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
}