package com.cxdai.console.cgnotify.entity;

import java.math.BigDecimal;
import java.util.Date;

public class EReconHeader {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_header.ID
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_header.TARGET_TYPE
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    private Integer targetType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_header.TARGET_ID
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    private String targetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_header.TARGET_NAME
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    private String targetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_header.STATUS
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_header.YES_NUM
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    private Integer yesNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_header.YES_MONEY
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    private BigDecimal yesMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_header.NO_NUM
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    private Integer noNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_header.NO_MONEY
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    private BigDecimal noMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_header.ADDUSER
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    private Integer adduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_header.ADDTIME
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_header.REMARK
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_recon_header.FILE_NAME
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    private String fileName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_header.ID
     *
     * @return the value of e_recon_header.ID
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_header.ID
     *
     * @param id the value for e_recon_header.ID
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_header.TARGET_TYPE
     *
     * @return the value of e_recon_header.TARGET_TYPE
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public Integer getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_header.TARGET_TYPE
     *
     * @param targetType the value for e_recon_header.TARGET_TYPE
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public void setTargetType(Integer targetType) {
        this.targetType = targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_header.TARGET_ID
     *
     * @return the value of e_recon_header.TARGET_ID
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public String getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_header.TARGET_ID
     *
     * @param targetId the value for e_recon_header.TARGET_ID
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public void setTargetId(String targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_header.TARGET_NAME
     *
     * @return the value of e_recon_header.TARGET_NAME
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public String getTargetName() {
        return targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_header.TARGET_NAME
     *
     * @param targetName the value for e_recon_header.TARGET_NAME
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public void setTargetName(String targetName) {
        this.targetName = targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_header.STATUS
     *
     * @return the value of e_recon_header.STATUS
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_header.STATUS
     *
     * @param status the value for e_recon_header.STATUS
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_header.YES_NUM
     *
     * @return the value of e_recon_header.YES_NUM
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public Integer getYesNum() {
        return yesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_header.YES_NUM
     *
     * @param yesNum the value for e_recon_header.YES_NUM
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public void setYesNum(Integer yesNum) {
        this.yesNum = yesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_header.YES_MONEY
     *
     * @return the value of e_recon_header.YES_MONEY
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public BigDecimal getYesMoney() {
        return yesMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_header.YES_MONEY
     *
     * @param yesMoney the value for e_recon_header.YES_MONEY
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public void setYesMoney(BigDecimal yesMoney) {
        this.yesMoney = yesMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_header.NO_NUM
     *
     * @return the value of e_recon_header.NO_NUM
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public Integer getNoNum() {
        return noNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_header.NO_NUM
     *
     * @param noNum the value for e_recon_header.NO_NUM
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public void setNoNum(Integer noNum) {
        this.noNum = noNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_header.NO_MONEY
     *
     * @return the value of e_recon_header.NO_MONEY
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public BigDecimal getNoMoney() {
        return noMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_header.NO_MONEY
     *
     * @param noMoney the value for e_recon_header.NO_MONEY
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public void setNoMoney(BigDecimal noMoney) {
        this.noMoney = noMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_header.ADDUSER
     *
     * @return the value of e_recon_header.ADDUSER
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public Integer getAdduser() {
        return adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_header.ADDUSER
     *
     * @param adduser the value for e_recon_header.ADDUSER
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public void setAdduser(Integer adduser) {
        this.adduser = adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_header.ADDTIME
     *
     * @return the value of e_recon_header.ADDTIME
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_header.ADDTIME
     *
     * @param addtime the value for e_recon_header.ADDTIME
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_header.REMARK
     *
     * @return the value of e_recon_header.REMARK
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_header.REMARK
     *
     * @param remark the value for e_recon_header.REMARK
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_recon_header.FILE_NAME
     *
     * @return the value of e_recon_header.FILE_NAME
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_recon_header.FILE_NAME
     *
     * @param fileName the value for e_recon_header.FILE_NAME
     *
     * @mbggenerated Thu May 26 10:05:44 CST 2016
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
}