package com.cxdai.console.borrow.manage.mapper;

import java.util.List;
import java.util.Map;

import com.cxdai.console.borrow.manage.vo.EFundRepayMent;
import com.cxdai.console.borrow.manage.vo.EFundRepayMentCnd;
import com.cxdai.console.borrow.manage.vo.RepayResBiz;
import org.apache.ibatis.annotations.Param;


public interface EFundRepayMentMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_fund_repayment
     *
     * @mbggenerated Tue May 17 14:51:20 CST 2016
     */
    int insert(EFundRepayMent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_fund_repayment
     *
     * @mbggenerated Tue May 17 14:51:20 CST 2016
     */
    int insertSelective(EFundRepayMent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_fund_repayment
     *
     * @mbggenerated Tue May 17 14:51:20 CST 2016
     */
    public EFundRepayMent selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_fund_repayment
     *
     * @mbggenerated Tue May 17 14:51:20 CST 2016
     */
    public int updateByPrimaryKeySelective(EFundRepayMent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_fund_repayment
     *
     * @mbggenerated Tue May 17 14:51:20 CST 2016
     */
    public int updateByPrimaryKey(EFundRepayMent record);
    
    public List<EFundRepayMent> selectByRepayId(Map<String, Object> parameter);
    
    public void updateByResponse(EFundRepayMentCnd efundCnd);
    
    public int queryRepayMentCount(EFundRepayMentCnd efundCnd);

    public EFundRepayMent selectCollectionId(Map<String, Object> parameter);

    /**
     *找出最近一条银行已处理的上报记录
     * @param eProject
     * @return
     */
    public EFundRepayMent queryEfendRepayByProject(@Param("eProject") String eProject);

}