package com.cxdai.console.base.mapper;

import com.cxdai.console.base.entity.BaseEBankInfo;

public interface BaseEBankInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_bankinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_bankinfo
     *
     * @mbggenerated
     */
    int insert(BaseEBankInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_bankinfo
     *
     * @mbggenerated
     */
    int insertSelective(BaseEBankInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_bankinfo
     *
     * @mbggenerated
     */
    BaseEBankInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_bankinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseEBankInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_bankinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseEBankInfo record);

    /**
     * 根据用户ID查询
     * @param id
     * @return
     */
    BaseEBankInfo selectByUserId(Integer id);

    /**
     * 根据用户ID查询并锁定
     * @param id
     * @return
     */
    BaseEBankInfo selectByUserIdForUpdate(Integer id);
    
    
    String selectByUserName(String userName);


    int updateByUserId(BaseEBankInfo record);
}